use_frameworks!
target ‘RunFast’ do
pod 'AFNetworking', '~> 3.1.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'SDWebImage', '~> 3.7.6'
pod 'IQKeyboardManager', '~> 4.0.3'
pod 'Masonry', '~> 1.0.1'
pod 'YYModel', '~> 1.0.3'
pod 'MJRefresh', '~> 3.1.0'
pod 'FMDB', '~> 2.6.2'
end
